name: Test Repo
on: [push]
jobs: 
  run-app-testing: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: '18'
      - run: npm install 
      - run: npm run test
  deploy-application:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: '18'
      - run: npm install 
      - run: npm run build 
      - run: echo 'Deploying...'
